### ISSUE TITLE
Replace `stahnma/epel` with `puppet/epel`

### ISSUE THREAD

**Issue by david22swan** [puppetlabs/puppetlabs-postgresql#1344]
## Describe the Bug
The spec_helper_local_acceptance set up relies on the puppet module epel, however we are currently using the original deprecated version `stahnma/epel` rather than the currently maintained `puppet/epel`.
## Expected Behavior
For the code to be update to use `puppet/epel`

**Comment by ekohl** [comment]
This module doesn't use epel. I think you intended to open this against the apache module.

**Comment by david22swan** [comment]
Yeh, my bad

**Comment by david22swan** [comment]
https://github.com/puppetlabs/puppetlabs-apache/issues/2244
