### ISSUE TITLE
Module is still using old puppet types

### ISSUE THREAD

**Issue by david22swan** [puppetlabs/puppetlabs-postgresql#1364]
## Use Case
The module is still using the old form of Puppet types.
While this will not cause any outright errors, it does make the module more difficult to pick up and alter in the future as the way in which it is written is no longer standard and will be less familiar to people going forward.

## Describe the Solution You Would Like
The existing types should be moved to the current format.

**Comment by david22swan** [comment]
I think I may have confused myself.........
Gonna close this and rethink what I meant

**Comment by ekohl** [comment]
Perhaps you meant parser functions? Though I don't see those here either.
