### ISSUE TITLE
Wrong data type for postgresql::server::config_entry::value

### ISSUE THREAD

**Issue by smoeding** [puppetlabs/puppetlabs-postgresql#1423]
## Describe the Bug
PostgreSQL has a couple of parameters that take a floating point value (see https://www.postgresql.org/docs/15/runtime-config-query.html for example). These parameters can't be managed any more as `postgresql::server::config_entry::value` can only be a String or an Integer after commit 655ac5e.  

## Expected Behavior
We should be able to manage parameters needing a Float value. The data type for `config` should probably include `Float` (or `Numeric` as a replacement for `Integer`).

## Steps to Reproduce
Use the following snippet in your manifest:
```
postgresql::server::config_entry { 'random_page_cost':
  value => 4.0,
}
```

## Environment
 - Version 7.24.0
 - Platform Debian 11

**Comment by jordanbreen28** [comment]
Thanks for raising this @smoeding.
We will work to get this resolved and released.
