### ISSUE TITLE
[9.0.1] breaks listen_addresses and increase the chance off an miss configuration

### ISSUE THREAD

**Issue by tuxmaster5000** [puppetlabs/puppetlabs-postgresql#1426]
Before version 9 the parameter listen_addresses was an array, so existing code will not work any more:
`Class[Postgresql::Server]: parameter 'listen_addresses' expects a value of type Undef or String, got Tuple`
Change the array to an string will increase the chance of an miss configuration, because when set multiple address they must be an  comma-separated list.  So the old behaviour joining the array with an  comma as the seperator makes more sense.
The last working one was 8.2.1

**Comment by jordanbreen28** [comment]
Thanks for raising this @tuxmaster5000! Will work to get this fixed and released ASAP.

Introduced in https://github.com/puppetlabs/puppetlabs-postgresql/pull/1397

**Comment by tuxmaster5000** [comment]
@jordanbreen28  9.0.2 don't fix this :(
`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Postgresql::Server::Config_entry[listen_addresses]: parameter 'value' expects a value of type Undef, String, or Numeric, got Tuple (file: /etc/puppetlabs/code/environments/production/modules/postgresql/manifests/server/instance/config.pp, line: 152)`

**Comment by jordanbreen28** [comment]
@tuxmaster5000 ah! Let’s take a look.. can you check that your passing the values to listen_addresses in the form of an Array  of strings `['0.0.0.0', '127.0.0.1']` or string `'127.0.0.1'`

**Comment by tuxmaster5000** [comment]
The  listen_addresses is an array in my case. Like it was working in the 8'er series.

**Comment by ekohl** [comment]
https://github.com/puppetlabs/puppetlabs-postgresql/pull/1430#discussion_r1187332194

**Comment by jordanbreen28** [comment]
@tuxmaster5000 okay this should be it now... 
v9.0.3 on the forge should fix this! 🤞 
Thanks for being thorough and spotting my oversight!
