### ISSUE TITLE
Stdlib::IP::Address::V6::CIDR does not exist prior to stdlib 5.2.0

### ISSUE THREAD

**Issue by markasammut** [puppetlabs/puppetlabs-postgresql#1427]
## Describe the Bug
Module fails to compile with "parameter 'address' references an unresolved type 'Stdlib::IP::Address::V6::CIDR'" in installations were stdlib module < 5.2.0 is being used. Dependency in metadata.json still describes stdlib down to  4.13.1 to be acceptable

## Expected Behavior
Catalog compilation with correct dependency parameters for other modules

## Steps to Reproduce
1. Run module with stdlib module >=4.13.1 and < 5.2.0

## Environment
Any

**Comment by jordanbreen28** [comment]
Hey @markasammut,

[puppetlabs-postgresql](https://forge.puppet.com/modules/puppetlabs/postgresql) v9.0.2 is now available on the forge with a fix in place for this.

Thanks for raising this.
