### ISSUE TITLE
Identical $port_override behaviour

### ISSUE THREAD

**Issue by SimonHoenscheid** [puppetlabs/puppetlabs-postgresql#1468]
## Describe the Bug
Varous defines use  the $port_override variable, parameter and condition should behave thje same

See: Slack thread
https://puppetcommunity.slack.com/archives/C0W298S9G/p1692947310149489

Diskussed this with David Sandilands and he asked for an issue and PR.

**Comment by ekohl** [comment]
> See: Slack thread
> https://puppetcommunity.slack.com/archives/C0W298S9G/p1692947310149489

Slack threads are not readable if you don't have an account. If it's relevant, please make sure that all the relevant information is in the issue. In this case it's fine since you submitted the PR directly (and then I even consider the issue redundant), but noting for the future.

**Comment by SimonHoenscheid** [comment]
#1498
