### ISSUE TITLE
Regression: postgresql::postgresql_password() broken on 10.0.0

### ISSUE THREAD

**Issue by sircubbi** [puppetlabs/puppetlabs-postgresql#1528]
## Describe the Bug
Updating to 10.0.0 breaks the usage of  `postgresql::postgresql_password()`. Might be related to #1515 (`md5` not supported on modern systems)

## Steps to Reproduce
After updating to 10.0.0 all calls to `postgresql::postgresql_password()` fail with `Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Function Call, failed to coerce org.jruby.RubySymbol to java.lang.String`

## Environment
 - Version of postgresql-Mod: 10.0.0
 - Version of puppet: 8.2.0
 - Platform: Rocky Linux 9

## Additional Context
Did not yet debug all of the code changes, but I suspect the switch of using `md5` as the default hash-method now. Seeing a Java-error there rings a least a bell with the modern security policies that are part of newer systems like EL9.

**Comment by deemon87** [comment]
+1
