### ISSUE TITLE
Reload the configuration when service_manage is false

### ISSUE THREAD

**Issue by vaol** [puppetlabs/puppetlabs-postgresql#1558]
## Describe the Bug
When **postgresql::params::service_manage** is set to **false**, the PostgreSQL configuration is not reloaded.
It seems to be because default **postgresql::server::service_reload** is using systemctl to trigger the reload, however it is not started in this case.

## Expected Behavior
The PostgreSQL configuration might be needed to be reloaded with pg_ctl -D $data_directory in this case.

## Environment
 - 10.0.2
 - Platform Almalinux 9.2

**Comment by ekohl** [comment]
There is an exec for this in [postgresql::server::instance::reload](https://github.com/puppetlabs/puppetlabs-postgresql/blob/main/manifests/server/instance/reload.pp) that's marked as `refreshonly` so perhaps that's not properly sent.

If this is intentional, I'd say that it should at least be documented.

**Comment by vaol** [comment]
Hello,

Thanks for the quick feedback.

I've managed by setting the reload_command as follow:
```puppet
  $service_reload_params = $db_pg_service_manage ? {
    true  => {},
    false => {
      service_reload => "su - postgres -c \"/usr/pgsql-${db_pg_version}/bin/pg_ctl -D /data/postgres/${db_pg_version}/pg_data reload\"",
      service_status => '/bin/true',
    },
  }

  class { 'postgresql::server':
    listen_addresses          => ['*'],
    postgres_password         => $db_master_pass,
    config_entries            => $final_config,
    service_restart_on_change => false,
    service_manage            => $db_pg_service_manage,
    service_ensure            => 'running',
    *                         => $service_reload_params,
    require                   => Exec['ssl_certificate'],
  }
```

I first though that it would be beneficial to build the reload command depending on the fact that the service is managed or not, but it might not be necessary as I consider it as an edge case.

What do you think ?

**Comment by ekohl** [comment]
I'm not sure since I never really thought about the case of unmanaged services. For my setups it's not what I want, so I really don't know what's best.

**Comment by smortex** [comment]
> For my setups it's not what I want

Same here, if I set `manage_service => false`, I expect the service to **not** be started / restarted / notified in any case and handle this by hand outside of Puppet.

**Comment by vaol** [comment]
Thank you for the feedbacks, I am happy the way I implemented so far, hence closing this issue.
