### ISSUE TITLE
GPG Key no longer valid for RPMS

### ISSUE THREAD

**Issue by jonathannewman** [puppetlabs/puppetlabs-postgresql#1565]
## Describe the Bug
Postgres org changed all the GPG keys as of January 3rd, so the Postgres module is no longer able to install Postgres on some centos based platforms.

e.g.
```
The GPG keys listed for the "PostgreSQL 11 7 - x86_64" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.
```

See https://yum.postgresql.org/news/pgdg-rpm-repo-gpg-key-update/

## Expected Behavior
GPG key validation works.

## Steps to Reproduce
On a new centos 7 system:
```
sudo rpm -Uvh https://yum.puppet.com/puppet7-release-el-7.noarch.rpm
yum install ca-certificates
yum install puppet
puppet module install puppetlabs-postgresql
puppet apply --execute "class { 'postgresql::globals': manage_package_repo => true, version=> '14' } class { 'postgresql::server':}"
```

## Environment
 - Platform centos7, redhat 7, redhat 8, almalinux8, rocky8

**Comment by jonathannewman** [comment]
I believe this needs to be updated:  https://github.com/puppetlabs/puppetlabs-postgresql/blob/010ed69eef927200d9058f9e5a3e00442bfa86d8/files/RPM-GPG-KEY-PGDG

**Comment by vaol** [comment]
On my environment, I fixed it with the changes available in [PR1566](https://github.com/puppetlabs/puppetlabs-postgresql/pull/1566). Can you check ?

**Comment by jonathannewman** [comment]
Thanks!  I'm trying to validate it now.
