### ISSUE TITLE
Using same default template as the PostgreSQL default

### ISSUE THREAD

**Issue by harbulot** [puppetlabs/puppetlabs-postgresql#157]
The [default template used by PostgreSQL](http://www.postgresql.org/docs/8.4/static/manage-ag-templatedbs.html) is `template1`. Yet, the [current `createdb` command specifies `template0` explicitly](https://github.com/puppetlabs/puppet-postgresql/blob/501289394ab48c427946bb4a3c2af983bb8e8e7a/manifests/database.pp#L50).

It would probably be better to keep the PostgreSQL default values in general. Perhaps an extra optional parameter similar to the "locale" parameter could be used for those who want to use a non-default value.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
