### ISSUE TITLE
GPG Key Outdated on Tag 8.2.1

### ISSUE THREAD

**Issue by haligan** [puppetlabs/puppetlabs-postgresql#1573]
## Describe the Bug
Tag 8.2.1 uses the old GPG for the repository in files/RPM-GPG-KEY-PGDG that changed in January 2024

## Expected Behavior
The file to be correct, so that the module works correctly when it installs postgres

## Steps to Reproduce
Install 8.2.1 tag for puppet.  Run the agent on client.  Fails for GPG mismatch.

## Environment
- Main Branch Tag V.8.2.1

## Additional Context
I've tried to submit pull requests to main tag/v8.2.1 and to the gpg_backport_branch and I get 403.  There are dependencies we require for the stdlib which breaks after v8.2.1 and therefore would like to either have a tag for v8.2.2 or just to modify tag v8.2.1.

Please let me know if there is a way I can do this.  As I've mentioned I don't have the authorization to submit a PR for this and also the contrib link in the contribute.md is 404ing.  I'd like to help out if I can.

**Comment by vaol** [comment]
Hi, I believe this has been managed on #1566

**Comment by vijay-bais** [comment]
Hi All,

When we installed module using command 'puppet module install puppetlabs-postgresql --version 8.2.1' then module having different file modules/postgresql/files/RPM-GPG-KEY-PGDG content then module project git URL https://github.com/puppetlabs/puppetlabs-postgresql/blob/main/files/RPM-GPG-KEY-PGDG

`#puppet module list
/etc/puppetlabs/code/environments/production/modules
├── puppetlabs-apt (v9.0.2)
├── puppetlabs-concat (v7.4.0)
├── puppetlabs-postgresql (v8.2.1)
└── puppetlabs-stdlib (v8.6.0)
/etc/puppetlabs/code/modules (no modules installed)
/opt/puppetlabs/puppet/modules (no modules installed)
#
#md5sum /etc/puppetlabs/code/environments/production/modules/postgresql/files/RPM-GPG-KEY-PGDG
78b5db170d33f80ad5a47863a7476b22  /etc/puppetlabs/code/environments/production/modules/postgresql/files/RPM-GPG-KEY-PGDG
#
#md5sum /etc/puppetlabs/code/environments/production/modules/postgresql/files/RPM-GPG-KEY-PGDG
78b5db170d33f80ad5a47863a7476b22  /etc/puppetlabs/code/environments/production/modules/postgresql/files/RPM-GPG-KEY-PGDG
#`

**Comment by ekohl** [comment]
Version 8.2.1 is no longer supported. It is resolved in #1566 so you'll need to update to at least 10.0.3.
