### ISSUE TITLE
Yum repo on Red Hat Enterprise 8 doesn't exist

### ISSUE THREAD

**Issue by TomG83** [puppetlabs/puppetlabs-postgresql#1606]
## Describe the Bug
Yum repo on Red Hat Enterprise 8 doesn't exist:

Status code: 404 for https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-8-x86_64/repodata/repomd.xml

## Expected Behavior
Install and update package from repository

## Steps to Reproduce
1. manage_package_repo => false, on postgresql::globals class
2. Perform puppet agent run on target node and wait until PostgreSQL repo is added on Red Hat Enterprise 8
3. Perform yum update

## Environment
 - Version 10.3.0
 - Platform Red Hat Enterprise 8

**Comment by ekohl** [comment]
Looks like PostgreSQL 10 is just removed altogether since it's not listed on https://download.postgresql.org/pub/repos/yum/ but that's not anything this module can do anything about. You need to pass a version that is supported by PostgreSQL.

> manage_package_repo => false, on postgresql::globals class

Do you mean `true`?

**Comment by TomG83** [comment]
Sorry for the mistake, I indeed mean true
