### ISSUE TITLE
Complete the documentation

### ISSUE THREAD

**Issue by ggeldenhuis** [puppetlabs/puppetlabs-postgresql#1608]
I wanted to know what part of the module I would use to set the listen_addresses parameter that is configured in postgresql.conf and naturally I checked out the example code that is part of the module. Instead I had to inspect the code and clearly missed the reference page because I was searching the page in chrome for listen keyword and found nada.

The expectation is that all the documentation is available without having to click through deeper levels.

**Comment by kenyon** [comment]
The documentation is designed to be viewed on https://forge.puppet.com/modules/puppetlabs/postgresql/reference
