### ISSUE TITLE
postgresql service will not start due to permission denied on postgresql_puppet_extras.conf

### ISSUE THREAD

**Issue by lfisher47** [puppetlabs/puppetlabs-postgresql#181]
I am running under a umask of 077 so all files are created with minimal permissions.

When we touch the file postgresql_puppet_extras.conf using an exec, we are setting the permissions based on the current runner of the command (root) and permissions based on umask, so in my case 600.  I was then unable to start the service because postgresql did not have access to this file.

In order to fix this issue, I added 

file { 'postgresql_puppet_extras.conf':
      path  => "$datadir/postgresql_puppet_extras.conf",
      owner => $user,
      group => $group,
    }

after we create the file, but I'm not sure why we aren't using the file type to begin with and instead are touching the file.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
