### ISSUE TITLE
Encoding set to SQL_ASCII on Debian family if package installed via puppet.

### ISSUE THREAD

**Issue by mcanevet** [puppetlabs/puppetlabs-postgresql#196]
This issue is maybe related to #178 and #185 .

My system locale is set to en_GB.UTF-8.

If I install postgresql using apt-get command, I get the default database create with UTF8 encoding (which is what I want), but if I do it via puppet the database is created with SQL_ASCII probably because of this: http://projects.puppetlabs.com/issues/11860.

I think that if there is no way to workaround this puppet bug, we have to destroy the default cluster (if there is only databases template0, template1 and postgres and if Encoding is not requested encoding) en recreate it with postgresql::initdb.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
