### ISSUE TITLE
postgresql_reload depends on 'service' which is not present on all distros

### ISSUE THREAD

**Issue by direvus** [puppetlabs/puppetlabs-postgresql#226]
I am using this module under Gentoo, and most things seem to be working with a little massaging required.

The one thing that sticks out is the calls to Exec[postgresql_reload] that get triggered on changes to pg_hba.  This Exec is hardcoded to use the 'service' command (see manifests/server.pp:87), which appears to be a RedHat/Debian specific thing -- at least, Gentoo doesn't have it.  The correct way to reload postgres on Gentoo is e.g., `/etc/init.d/postgresql-9.2 reload`.

I think this could be solved quite easily by allowing a 'reload_command' parameter to be passed into postgresql::server.  Those of us who do not have a 'service' can just override it to suit.

Let me know if you'd prefer me to provide a pull request, I'd be happy to do so.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
