### ISSUE TITLE
postgresql module generates .dot file (graph) with invalid syntax 

### ISSUE THREAD

**Issue by carthik** [puppetlabs/puppetlabs-postgresql#246]
When using the postgresql module, the graphs generated by Puppet (in the dot format) have syntax errors.

Here's an example of the error from a dot file:

```
Error: relationships.dot:1033: syntax error near line 1033
context:     "Postgresql_psql[GRANT all ON database >>>  "pe- <<< puppetdb" TO "pe-puppetdb"]" [
```

The fixed version would look like the following:

```
Error: relationships.dot:1033: syntax error near line 1033
context:     "Postgresql_psql[GRANT all ON database >>>  'pe- <<< puppetdb' TO 'pe-puppetdb']" [
```

Can't have double quotes inside the double quotes.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
