### ISSUE TITLE
Installs 9.1 when 9.3 already installed, and no version specified

### ISSUE THREAD

**Issue by teknotus** [puppetlabs/puppetlabs-postgresql#266]
With the simple puppet manifest of

``` puppet
class { 'postgresql::server': }
```

when PostgreSQL 9.3 is installed results in an action of installing 9.1 with the same configured port number. Thus the new server cannot start, and the functioning server may fail to start the next time init scripts are run.

Defaults for database management should be safe.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
