### ISSUE TITLE
postgresql::server::version is only partially used

### ISSUE THREAD

**Issue by kitchen** [puppetlabs/puppetlabs-postgresql#277]
There are a number of places where `$postgresql::server::version` is used, but things like `$postgresql::server::install::package_name` use `$postgresql::server::package_name`, which comes from `$postgresql::params::server_package_name`, which uses (at least in the case of debian) `$postgresql::params::version` which defaults to `$postgresql::globals::globals_version` which does _not_ look at `$postgresql::server::version`

So, either the package name for server should be figured out in `postgresql::server` class, or the things using `$postgresql::server::version` should be changed to look at `$postgresql::params::version`, maybe, and the `$postgresql::server::version` parameter should just go away entirely (it's not actually used within the `$postgresql::server` class.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.\n\nWe're going to close it but please do raise another issue if the issue still persists. 😄
