### ISSUE TITLE
Custom datadir in postgresql::globals gets ignored or produce an error

### ISSUE THREAD

**Issue by dgolja** [puppetlabs/puppetlabs-postgresql#305]
Hello,

so If you declare the _datadir_ attribute in _postgresql::globals_ the new data dir or get ignored if running on Ubuntu (12.04/Debian) or produce an error if executed on CentOS 64.

Code to reproduce the error:

``` puppet
class { 'postgresql::globals':
     datadir  => '/opt/custom_dir',
   } ->

  class { 'postgresql::server': }
```

I tired that on vagrant with vagrant-puppetlabs images.

**_Ubuntu/Debian:**_
- if you run the module with the $manage_package_repo to false (default value) first of all the postgresql::server::initdb exec part which initialize the data structure never get executed. Also the value of the confdir in params for Debian is fixed to the default path which is wrong. So the module will basically ignore that parameter and still evertyhing will work fine. However that's an easy fix (PR 304 submitted), but to properly start the service with the custom data dir the upstart scripts has to be changed too. I am happy to do that, however it's more a design decision or if you would like to overwrite the init scripts directly from the module via files or templates or maybe add the right param via augeas or smth else. 

**_RedHat/CentOS:**_
- the postgres service can't be started, because even if the right datadir initdb is initialized the init.d script value for the PGDATA is wrong. To fix that problem it's enough to adjust the PGDATA value in /etc/init.d/postgresql, however again the question is or to rewrite/push the init script from the module itself or try to use augeas or something else.

Error:
Error: Could not start Service[postgresqld]: Execution of '/sbin/service postgresql start' returned 1: 
Error: /Stage[main]/Postgresql::Server::Service/Service[postgresqld]/ensure: change from stopped to running failed: Could not start Service[postgresqld]: Execution of '/sbin/service postgresql start' returned 1:

cheers

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
