### ISSUE TITLE
Why ensure => 'stopped' is not available for the Postgres server?

### ISSUE THREAD

**Issue by gbartolini** [puppetlabs/puppetlabs-postgresql#315]
Is there a reason why the ensure property for the postgresql::server class does not allow to force a Postgres server to be there but not running?

Maybe it is there and I am looking at the wrong options. In that case, I apologise in advance. Thank you.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
