### ISSUE TITLE
Validate permissions of /var/lib/psql

### ISSUE THREAD

**Issue by ITBlogger** [puppetlabs/puppetlabs-postgresql#321]
Hi All,

On systems with a more restrictive umask the /var/lib/psql directory tree isn't getting set up with the appropriate owners and permissions.

Please modify the module so that it enforces the proper ownership and permissions of all files and directories in /var/lib/psql.

Thanks,

Alex

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
