### ISSUE TITLE
variables do not conform to Puppet 3.4 naming rules

### ISSUE THREAD

**Issue by richardvanbergen** [puppetlabs/puppetlabs-postgresql#332]
This looks to be the same issue that is affecting puppetlabs-apache too. Basically puppet 3.4 has changed it so you can begin variable names with an underscore.

https://github.com/puppetlabs/puppetlabs-apache/issues/538

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
