### ISSUE TITLE
Deprecation of Puppet::Util::SUIDManager.run_and_capture not fixed completely

### ISSUE THREAD

**Issue by lieutdan13** [puppetlabs/puppetlabs-postgresql#338]
The deprecation of Puppet::Util::SUIDManager.run_and_capture occurred in puppet version 3.4.0. The comparison in the fix in PR #320 is to version 4. I have puppet 3.4.1 and I'm still receiving the warning in lib/puppet/provider/postgresql_psql/ruby.rb:79

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
