### ISSUE TITLE
tutorial error; user / group "dan" is never mentioned

### ISSUE THREAD

**Issue by erikbergsma** [puppetlabs/puppetlabs-postgresql#367]
the tutorial in README.md says:
_In this example, you would grant ALL privileges on the test1 database and on the my_table table of the test2 database to the user or group specified by dan._

only there is no mention of this "dan" user anywhere, which makes the tutorial a bit hard to read / follow.

broken file:
https://github.com/puppetlabs/puppetlabs-postgresql/blob/master/README.md

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
