### ISSUE TITLE
Using Augeas

### ISSUE THREAD

**Issue by antaflos** [puppetlabs/puppetlabs-postgresql#73]
Hi, 

I thought I'd open an issue here to discuss whether and how to use Augeas for managing `postgresql.conf` and `pg_hba.conf`.

Augeas 1.0.0 has been released recently and I know that packages are available at least for Ubuntu from @raphink's PPA (https://launchpad.net/~raphink/+archive/augeas). Ubuntu 13.04 will have official Augeas 1.0.0 packages. I don't know how support looks on RHEL or other systems.

Augeas 1.0.0 now has extended lenses for both `postgresql.conf` and `pg_hba.conf` which look pretty good to me, but I have yet to test them thoroughly with Puppet. So I wonder: is it worthwhile to pursue using Augeas to manage these important files, or are people happier with the current template-based approach and the ideas for `postgresql.conf` discussed in issue #26 (I wanted to take a crack at this, but haven't had the time yet, unfortunately)?

The advantages or Augeas are, in my opinion, clear: no need for complex template constructs, we get syntax checks and support for all settings in `postgresql.conf` and also for all kinds of ACLs in `pg_hba.conf` without having to expose specific ACL types to the user and hiding or not supporting others (ipv4acls/ipv6acls vs unixacls, see PR #72). Using Augeas from within Puppet is easy enough, although in the end there might again be need for some kind of template/eruby hackery. 

One thing to consider is that Augeas 1.0.0 will probably not be available on most systems for quite some time so Augeas support in this module should only be used if `facter augeasversion >= 1.0.0`. For earlier versions the template approach for `pg_hba.conf` and `file_line` for `postgresql.conf` (issue #26) will remain the only option.

Another thing to consider is that Augeas can significantly slow down a Puppet run if it manages many configuration settings. 

And of course, as @jhoblitt has pointed out in PR #72 Augeas only manages specified settings, so manual edits to the configuration are, by design, still possible and not caught by Puppet.

So it might be necessary for the module user to be able to decide whether he wants to use Augeas or not. 

One or two new types will probably have to be defined, such as `postgresql::server::conf` (manages a setting in `postgresql.conf`) and `postgresql::server::hba` (manages an ACL in `pg_hba.conf`).

This could lead to something like this:

```
postgresql::server::conf { 
  'listen_addresses': value => '*';
  'port':             value => '5432';
  'max_connections':  value => '500';
}
```

And for `pg_hba.conf` the @camptocamp guys have already defined an IMHO reasonable type for ACLs, which would look somewhat like this:

```
postgresl::server::hba { 'access to some database for alice':
  ensure => present,
  type => 'host',
  database => 'some',
  user => 'alice',
  address => '10.0.0.0/16',
  method => 'md5',
}
```

But there would probably have to be a way to abstract and hide these declarations, or they would clutter up the user's manifests since they are a bit more verbose (and thus ugly) than the current `config_hash` approach.

Sorry for this lengthy braindump. Maybe someone has some comments or ideas, I'd love to hear them. I hope I find the time to test and experiment with this myself in the coming weeks.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
